### ISSUE TITLE
Codebase Review

### ISSUE THREAD

**Issue by Blade67** [Snayff/not_quite_paradise4#3]
# Codebase Review

## Coding style
Overall, I'd recommend making a coding-style document outlining expected style and consider investing time into making a custom formatter (or adapt an existing one).
- Move inspector comments (`##`) above variables & functions instead of inline
- Don't have an `_` in front of exported variables. `_` is usually used to mark variables as "private" or "unused".
- In some scripts `push_warning` and `assert` are used interchangeably. Consider sticking to one and making use of the `@tool` decorator to leverage the editor functionalities (ie. warnings).
- The early-return pattern isn't always used.
- Some variables infer typing from a function's return type. I'd suggest avoiding that since it still impacts performance, especially on functions called every (physics) process.

## Problems
- In some scripts `match` statements are used, but most of the cases are empty. Use the default `_:` case to capture all of them. This prevents unhandled cases in the future.
- Boon Banes:
  - Use `Resource`s to pass in the behaviour. Resources can be extended upon like classes, but can be reused and potentially composed if set up correctly.
- In the `spawner.gd`'s `spawn_scene` function, you pass a function to the `parent` argument. I recommend doing this. Pass in `null` and do a check if it's indeed `null`, then set it to that value.
- In the `tags.gd`'s `add_tag` and `add_tags` functions, the logic is reversed. It would never add a tag that isn't already on.
- In some cases there are `variable == 0` checks, where variable is a float. While unlikely, values can be negative so the use of `abs` is advised and using [`is_zero_approx`](https://docs.godotengine.org/en/stable/classes/class_%40globalscope.html#class-globalscope-method-is-zero-approx) or [`is_equal_approx`](https://docs.godotengine.org/en/stable/classes/class_%40globalscope.html#class-globalscope-method-is-equal-approx) would be suggested.

## Suggested changes
- Move longer inline set/get functions into their own functions instead of keeping them inline.
- Refactor `effect`s to be composable `Resource`s. This makes effects agnostic and more reusable.
  - Applies to: `Effect`, `EffectChain`, `EffectStatScalerData`, `SpawnSceneEffect`, `DealDamageEffect` and `ApplyStatModEffect`. Also, naming scheme!
- Refactor `boon_bane`s to be composable `Resource`s. This makes Boons agnostic and more reusable.
  - Applies to: `BoonBane`, `Exhaustion` and `Burn`
- Refactor `visuals/` to extend from a singular `VisualEffect` class to make it more composable. This makes visual effects agnostic and more reusable.
  - Applies to: `FlashComponent`, `OneShotAnimation`, `ScaleComponent` and `ShakeComponent`
- Refactor the `BoonBaneContainer` to export arrays that specify self (the parent) or `target` as the target.
- Use a radial spreading algorithm for the `add_projectile` function in `orbiter.gd`. That would solve the double-hit issue you pointed out.

## Interesting observations
- In `orbiter.gd` on line 59 you have the `@warning_ignore("unused_variable")` decorator with a comment saying "godot thinks i is unused for some reason" and I'm just as taken aback as you are. This makes no sense and seems to be a Linter issue on Godot's side. Weird bug, really.
- You use composition in some cases, but inheritance in others. While this isn't a bad thing, composable inheritance and inherited composability aren't the same! Sticking to one is advised!

## Suggested addons
- TODO Manager (Godot 4)
- BehaviourToolkit

## Suggested editor settings changes
- Change `text_editor/behavior/indent/type` to `Spaces` at size 4

**Comment by Snayff** [comment]
> Don't have an _ in front of exported variables. 

I try and keep local private members/vars prefixed with _ to keep the API interface clean. While exported, I still want those members only interacted with locally or by the editor. Does that seem OK?

**Comment by Snayff** [comment]
> some scripts push_warning and assert are used interchangeably.

My intention was that push warning is for stuff that might be an issue, but there is ambiguity, so we just warn, but everything else should be an assert. I think I might have some push_error still knocking about which needs to be changed to asserts. 


> Consider [...] making use of the @tool decorator to leverage the editor functionalities (ie. warnings).

I don't know much about this, can you elaborate and maybe provide an example, please?

**Comment by Snayff** [comment]
> The early-return pattern isn't always used.

And


> Some variables infer typing from a function's return type. I'd suggest avoiding that since it still impacts performance, especially on functions called every (physics) process.

Roger. Will fix.

**Comment by Snayff** [comment]
> In some scripts match statements are used, but most of the cases are empty.

Those should only be for placeholders for known gaps, such as when using an enum and we have a known value but have not yet written the code for handling. Is this still bad practice?

**Comment by Snayff** [comment]
> Boon Banes:
    Use Resources to pass in the behaviour. 

Can you provide an example, please? I have little experience fmwith resources and have found them super hard to use without issue.

**Comment by Snayff** [comment]
> In the spawner.gd's spawn_scene function, you pass a function to the parent argument. I recommend doing this. Pass in null and do a check if it's indeed null, then set it to that value.

Not clear on this. Will double check code and come back.

**Comment by Snayff** [comment]
> In the tags.gd's add_tag and add_tags functions, the logic is reversed. It would never add a tag that isn't already on.

Will fix.

**Comment by Snayff** [comment]
> Refactor effects to be composable Resources. This makes effects agnostic and more reusable.
    Applies to: Effect, EffectChain, EffectStatScalerData, SpawnSceneEffect, DealDamageEffect and ApplyStatModEffect. 

Can you elaborate and possible provide example, please? As before, resources and I are not yet friends. 


> Also, naming scheme!

What's up with the naming scheme? 😛

**Comment by Snayff** [comment]
> Refactor boon_banes to be composable Resources. This makes Boons agnostic and more reusable.
    Applies to: BoonBane, Exhaustion and Burn

As above, I'll need an example but I assume 1 example will cover all 3 mentions of moving to composable Resources.

**Comment by Snayff** [comment]
> Refactor visuals/ to extend from a singular VisualEffect class to make it more composable. This makes visual effects agnostic and more reusable.
    Applies to: FlashComponent, OneShotAnimation, ScaleComponent and ShakeComponent

**Comment by Snayff** [comment]
> Refactor the BoonBaneContainer to export arrays that specify self (the parent) or target as the target.

Can you elaborate on this one, please? What's the benefit of doing this?

**Comment by Snayff** [comment]
> Use a radial spreading algorithm for the add_projectile function in orbiter.gd. That would solve the double-hit issue you pointed out.

Roger!

**Comment by Snayff** [comment]
> You use composition in some cases, but inheritance in others. While this isn't a bad thing, composable inheritance and inherited composability aren't the same! Sticking to one is advised!

Will this naturally be more consistent after the composability changes you've recommended?

**Comment by Snayff** [comment]
>     TODO Manager (Godot 4)

Agreed! On my list to add. 

>    BehaviourToolkit

More than [beehave ](https://github.com/bitbrain/beehave)or [limboai](https://github.com/limbonaut/limboai)?

**Comment by Snayff** [comment]
> Change text_editor/behavior/indent/type to Spaces at size 4

...but tabs > spaces? 😉

**Comment by Blade67** [comment]
Covering your answer:

[[2335170492](https://github.com/Snayff/godot_combat_test/issues/3#issuecomment-2335170492)]
> I try and keep local private members/vars prefixed with _ to keep the API interface clean. While exported, I still want those members only interacted with locally or by the editor. Does that seem OK?

That's fair. Not ideal per-se, but fair. We'll see if we can find better solutions for this!

[[2335171102](https://github.com/Snayff/godot_combat_test/issues/3#issuecomment-2335171102)]
> My intention was that push warning is for stuff that might be an issue, but there is ambiguity, so we just warn, but everything else should be an assert. I think I might have some push_error still knocking about which needs to be changed to asserts.
> I don't know much about this, can you elaborate and maybe provide an example, please?

The `push_*` functions can display icons inside the tree view on runtime if the script is marked as a `@tool` script. This is useful during development for a nicer DX. Also, making those functions only be called in dev is advisable. Reduces the chances of things breaking in prod!

[[2335171600](https://github.com/Snayff/godot_combat_test/issues/3#issuecomment-2335171600)]
> Those should only be for placeholders for known gaps, such as when using an enum and we have a known value but have not yet written the code for handling. Is this still bad practice?

It really depends, generally you want to have a "catch all" case, even if just throws an error or a warning for unhandled cases. Ideally you'd always have an Enum or a fixed set of possible values, but that isn't always possible, hence the "catch all" solution.

[[2335171880](https://github.com/Snayff/godot_combat_test/issues/3#issuecomment-2335171880)] [[2335173794](https://github.com/Snayff/godot_combat_test/issues/3#issuecomment-2335173794)] [[2335190103](https://github.com/Snayff/godot_combat_test/issues/3#issuecomment-2335190103)]
> Can you provide an example, please? I have little experience with resources and have found them super hard to use without issue.
> As above, I'll need an example but I assume 1 example will cover all 3 mentions of moving to composable Resources.
> Can you elaborate and possible provide example, please? As before, resources and I are not yet friends.

I'll have the rewrite use them where applicable, you'll be able to see what I mean!

[[2335173794](https://github.com/Snayff/godot_combat_test/issues/3#issuecomment-2335173794)]
> What's up with the naming scheme? 😛

It's inconsistent. For example, Effects currently have names like Effect, EffectChain, EffectStatScalerData, SpawnSceneEffect, DealDamageEffect and ApplyStatModEffect. But all Effects should start with the same keyword, in this case "Effect". So "SpawnSceneEffect" would become "EffectSpawnScene" or "EffectSceneSpawn".

[[2335190388](https://github.com/Snayff/godot_combat_test/issues/3#issuecomment-2335190388)]
> I might need help with how to do this, as their interface is quite varied, but will have a go first.

This will likely be covered by the Resource refactor as well, although Visual Effects may be better suited for pure inheritance than composability!

[[2335190684](https://github.com/Snayff/godot_combat_test/issues/3#issuecomment-2335190684)]
> Can you elaborate on this one, please? What's the benefit of doing this?

Sure! Smaller code chunks that are agnostic to scene or situation make things more flexible. In this case we'd loop over the Boons and Banes and handle them in a kind of "event loop". This way stats can be applied from any actor/unit no matter the target and effect. This will most likely be included in the Resource refactor!

[[2335191409](https://github.com/Snayff/godot_combat_test/issues/3#issuecomment-2335191409)]
> Will this naturally be more consistent after the composability changes you've recommended?

Yes! As mentioned, mixing composability and inheritance isn't a bad thing. In fact, we'll be doing it going forward. The difference is how its handled. 

[[2335192667](https://github.com/Snayff/godot_combat_test/issues/3#issuecomment-2335192667)]
> More than [beehave ](https://github.com/bitbrain/beehave)or [limboai](https://github.com/limbonaut/limboai)?

Each have their pros and cons. I just know the creator of BehaviourToolkit, so it's a slight bias. I'll have to look through each of them first and see what fits this project best!

[[2335192938](https://github.com/Snayff/godot_combat_test/issues/3#issuecomment-2335192938)]
> ...but tabs > spaces? 😉

Personal preference, really. I generally just prefer spaces since it's easier to align multi-line functions and conditionals!

**Comment by Snayff** [comment]
> Use Resources to pass in the behaviour. Resources can be extended upon like classes, but can be reused and potentially composed if set up correctly.

> I'll have the rewrite use them where applicable, you'll be able to see what I mean!

I am not sure you'll have any cause, will you? Given what you'll be working on.

> It's inconsistent. For example, Effects currently have names like Effect, EffectChain, EffectStatScalerData, SpawnSceneEffect, DealDamageEffect and ApplyStatModEffect. But all Effects should start with the same keyword, in this case "Effect". So "SpawnSceneEffect" would become "EffectSpawnScene" or "EffectSceneSpawn".

I think their purpose is just unclear. The ones with `Effect` at the end are subclasses of `Effect`.  The others do something in relation to `Effect`, but are not one. I used to use the parent-class's name as a prefix, but have had feedback over time that its harder to understand as it isnt similar to natural language, e.g. `EffectDamage` vs `DamageEffect`. 

I think I'll rename to make clearer. 

> Refactor the BoonBaneContainer to export arrays that specify self (the parent) or target as the target.

> Smaller code chunks that are agnostic to scene or situation make things more flexible. In this case we'd loop over the Boons and Banes and handle them in a kind of "event loop". This way stats can be applied from any actor/unit no matter the target and effect. This will most likely be included in the Resource refactor!

Sorry, mate, I am still not sure what this refactor would look like. Maybe a pseudo code example?

> BehaviourToolkit

> Each have their pros and cons. I just know the creator of BehaviourToolkit, so it's a slight bias. I'll have to look through each of them first and see what fits this project best!

You're in charge of that whole area, so totally your call. I liked the non-node approach and the debugger of limboai, but those are definitely secondary considerations.

**Comment by Blade67** [comment]
> I am not sure you'll have any cause, will you? Given what you'll be working on.

This may or may not be the case depending on the rewrite!

> I think their purpose is just unclear. The ones with Effect at the end are subclasses of Effect. The others do something in relation to Effect, but are not one. I used to use the parent-class's name as a prefix, but have had feedback over time that its harder to understand as it isnt similar to natural language, e.g. EffectDamage vs DamageEffect.
>
> I think I'll rename to make clearer.

Code readability > lexical readability

> Sorry, mate, I am still not sure what this refactor would look like. Maybe a pseudo code example?

```gd
class_name Boon # Applies to Banes too
extends Resource

# turn into a get/set function with signal later to destroy once
# the effect expired
var active: bool = false

func _init() -> void:
    # insert shared boon properties

func trigger() -> void:
    # insert activation event
    if !active:
        active = true
        return
    _tick()

func _tick() -> void:
    # apply per-tick relevant effects
```

```gd
class_name Unit
extends Node2D

@export var boons: Array[Boon] = []

# insert your basic unit functions

func _process() -> void:
    # handle your process

    trigger_boon()

# do the same for Banes
func trigger_boon() -> void:
    for boon in boons:
        boon.trigger()
```

Something like this ensures a flexible approach of which Boons and Banes extend from their respective base classes, while being able to be stacked as a resource from the Unit (or any other relevant classes) and applied to itself or a target is given one.

> You're in charge of that whole area, so totally your call. I liked the non-node approach and the debugger of limboai, but those are definitely secondary considerations.

Yes sir! I'll be sure to check them all out and see which one is best suited for this project!
